package org.leng.object;

import org.junit.jupiter.api.Test;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class WarnEntryTest {

    @Test
    void constructor_withThreeArgs_assignsIdAndDefaultsRevokedToFalse() {
        WarnEntry entry = new WarnEntry("alice", "admin", 1000L, "spam");
        assertNotNull(entry.id());
        assertEquals("alice", entry.player());
        assertEquals("admin", entry.staff());
        assertEquals(1000L, entry.time());
        assertEquals("spam", entry.reason());
        assertFalse(entry.revoked());
    }

    @Test
    void constructor_withId_acceptsExplicitId() {
        WarnEntry entry = new WarnEntry("custom-id", "alice", "admin", 1000L, "spam");
        assertEquals("custom-id", entry.id());
        assertFalse(entry.revoked());
    }

    @Test
    void revoke_returnsNewInstanceWithRevokedTrue() {
        WarnEntry original = new WarnEntry("alice", "admin", 1000L, "spam");
        WarnEntry revoked = original.revoke();
        assertNotSame(original, revoked);
        assertFalse(original.revoked()); // 原对象不变
        assertTrue(revoked.revoked());
        assertEquals(original.id(), revoked.id());
    }

    @Test
    void unrevoke_returnsNewInstanceWithRevokedFalse() {
        WarnEntry revoked = new WarnEntry("alice", "admin", 1000L, "spam").revoke();
        WarnEntry restored = revoked.unrevoke();
        assertNotSame(revoked, restored);
        assertTrue(revoked.revoked());
        assertFalse(restored.revoked());
    }

    @Test
    void withReason_replacesReasonField() {
        WarnEntry original = new WarnEntry("alice", "admin", 1000L, "spam");
        WarnEntry updated = original.withReason("updated reason");
        assertEquals("spam", original.reason()); // 原对象不变
        assertEquals("updated reason", updated.reason());
        assertEquals(original.id(), updated.id());
        assertEquals(original.revoked(), updated.revoked());
    }

    @Test
    void recordRejectsNullRequiredFields() {
        assertThrows(NullPointerException.class, () -> new WarnEntry(null, "admin", 0L, "r"));
        assertThrows(NullPointerException.class, () -> new WarnEntry("alice", null, 0L, "r"));
        assertThrows(NullPointerException.class, () -> new WarnEntry("alice", "admin", 0L, null));
    }

    @Test
    void autoGeneratedId_isUuid() {
        WarnEntry entry = new WarnEntry("alice", "admin", 0L, "r");
        // 不抛异常就是合法 UUID
        assertDoesNotThrow(() -> UUID.fromString(entry.id()));
    }
}